// Generated by scripts/import-emulator-captures.py from the raw emulator captures.
import type { Device } from "../../types";

export const pixel10Pro: Device = {
  "slug": "pixel-10-pro",
  "name": "Pixel 10 Pro",
  "brand": "Google",
  "series": "Pixel",
  "formFactor": "bar",
  "releaseYear": 2025,
  "screens": [
    {
      "id": "main",
      "label": "Main",
      "diagonalInch": 6.3,
      "resolutionPx": {
        "width": 1280,
        "height": 2856
      },
      "logicalSizePx": {
        "width": 1280,
        "height": 2856
      },
      "captureOrientation": "portrait",
      "captureRotation": 0,
      "ppi": 495,
      "logicalSizeDp": {
        "width": 426.67,
        "height": 952
      },
      "densityDpi": 480,
      "cornerRadiiDp": {
        "topLeft": 52.33,
        "topRight": 52.33,
        "bottomRight": 52.33,
        "bottomLeft": 52.33
      },
      "cornerRadiiPx": {
        "topLeft": 157,
        "topRight": 157,
        "bottomRight": 157,
        "bottomLeft": 157
      },
      "insets": {
        "gesture": {
          "systemBars": {
            "top": 52,
            "right": 0,
            "bottom": 24,
            "left": 0
          },
          "systemBarsPx": {
            "top": 156,
            "right": 0,
            "bottom": 72,
            "left": 0
          },
          "displayCutout": {
            "top": 52,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 156,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "cutoutShape": {
            "xDp": 195.33,
            "yDp": 0,
            "widthDp": 36.33,
            "heightDp": 52,
            "rightDp": 195.0,
            "bottomDp": 900,
            "xPx": 586,
            "yPx": 0,
            "widthPx": 109,
            "heightPx": 156,
            "rightPx": 585,
            "bottomPx": 2700
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_10_pro device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Portrait rotation 0, default 480 dpi and font scale 1. InsetsProbe 1.5.0 reported a 1280×2856 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_10_pro",
              "skin": "pixel_10_pro",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-10-pro/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_10_pro profile, gestures",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-10-pro/emulator-2026-09-27/main-gesture.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        },
        "threeButton": {
          "systemBars": {
            "top": 52,
            "right": 0,
            "bottom": 48,
            "left": 0
          },
          "systemBarsPx": {
            "top": 156,
            "right": 0,
            "bottom": 144,
            "left": 0
          },
          "displayCutout": {
            "top": 52,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 156,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "cutoutShape": {
            "xDp": 195.33,
            "yDp": 0,
            "widthDp": 36.33,
            "heightDp": 52,
            "rightDp": 195.0,
            "bottomDp": 900,
            "xPx": 586,
            "yPx": 0,
            "widthPx": 109,
            "heightPx": 156,
            "rightPx": 585,
            "bottomPx": 2700
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_10_pro device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Portrait rotation 0, default 480 dpi and font scale 1. InsetsProbe 1.5.0 reported a 1280×2856 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_10_pro",
              "skin": "pixel_10_pro",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-10-pro/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_10_pro profile, 3-button",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-10-pro/emulator-2026-09-27/main-threeButton.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        }
      },
      "sources": [
        {
          "kind": "official",
          "label": "Google Pixel phone hardware tech specs",
          "url": "https://support.google.com/pixelphone/answer/7158570?hl=en",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "official",
          "label": "AOSP Android Emulator skin pixel_10_pro (Apache 2.0)",
          "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_10_pro",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_10_pro profile, gestures",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-10-pro/emulator-2026-09-27/main-gesture.json",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_10_pro profile, 3-button",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-10-pro/emulator-2026-09-27/main-threeButton.json",
          "retrievedAt": "2026-09-27"
        }
      ]
    }
  ],
  "sources": [
    {
      "kind": "official",
      "label": "Google Pixel phone hardware tech specs",
      "url": "https://support.google.com/pixelphone/answer/7158570?hl=en",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "official",
      "label": "AOSP Android Emulator skin pixel_10_pro (Apache 2.0)",
      "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_10_pro",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_10_pro profile, gestures",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-10-pro/emulator-2026-09-27/main-gesture.json",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_10_pro profile, 3-button",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-10-pro/emulator-2026-09-27/main-threeButton.json",
      "retrievedAt": "2026-09-27"
    }
  ]
};
