// Generated by scripts/import-emulator-captures.py; order is the sidebar order.
import type { Device } from "../types";
import { pixel10ProFold } from "./pixel-10-pro-fold";
import { pixel9ProFold } from "./pixel-9-pro-fold";
import { pixelFold } from "./pixel-fold";
import { pixel10a } from "./pixel-10a";
import { pixel10ProXl } from "./pixel-10-pro-xl";
import { pixel10Pro } from "./pixel-10-pro";
import { pixel10 } from "./pixel-10";
import { pixel9ProXl } from "./pixel-9-pro-xl";
import { pixel9Pro } from "./pixel-9-pro";
import { pixel9 } from "./pixel-9";
import { pixel9a } from "./pixel-9a";
import { pixel8Pro } from "./pixel-8-pro";
import { pixel8 } from "./pixel-8";
import { pixel8a } from "./pixel-8a";
import { pixel7Pro } from "./pixel-7-pro";
import { pixel7 } from "./pixel-7";
import { pixel7a } from "./pixel-7a";
import { pixel6Pro } from "./pixel-6-pro";
import { pixel6 } from "./pixel-6";
import { pixel6a } from "./pixel-6a";
import { pixel5 } from "./pixel-5";
import { pixel4a } from "./pixel-4a";
import { pixelTablet } from "./pixel-tablet";

export const pixelDevices: Device[] = [pixel10ProFold, pixel9ProFold, pixelFold, pixel10a, pixel10ProXl, pixel10Pro, pixel10, pixel9ProXl, pixel9Pro, pixel9, pixel9a, pixel8Pro, pixel8, pixel8a, pixel7Pro, pixel7, pixel7a, pixel6Pro, pixel6, pixel6a, pixel5, pixel4a, pixelTablet];
