// Generated by scripts/import-emulator-captures.py; order is the sidebar order.
import type { Device } from "../types";
import { pixel10ProFold } from "./pixel-10-pro-fold";
import { pixel9ProFold } from "./pixel-9-pro-fold";
import { pixelFold } from "./pixel-fold";
import { pixel10Pro } from "./pixel-10-pro";
import { pixel10 } from "./pixel-10";
import { pixel9ProXl } from "./pixel-9-pro-xl";
import { pixel9Pro } from "./pixel-9-pro";
import { pixel9 } from "./pixel-9";
import { pixel9a } from "./pixel-9a";
import { pixelTablet } from "./pixel-tablet";

export const pixelDevices: Device[] = [pixel10ProFold, pixel9ProFold, pixelFold, pixel10Pro, pixel10, pixel9ProXl, pixel9Pro, pixel9, pixel9a, pixelTablet];
