// Generated by scripts/import-emulator-captures.py from the raw emulator captures.
import type { Device } from "../../types";

export const pixel9ProFold: Device = {
  "slug": "pixel-9-pro-fold",
  "name": "Pixel 9 Pro Fold",
  "brand": "Google",
  "series": "Pixel Fold",
  "formFactor": "foldable-book",
  "chassisMm": {
    "unfoldedWidth": 150.2,
    "unfoldedDepth": 5.1,
    "foldedDepth": 10.5,
    "source": {
      "kind": "official",
      "label": "Google Pixel phone hardware tech specs",
      "url": "https://support.google.com/pixelphone/answer/7158570?hl=en",
      "retrievedAt": "2026-09-27"
    }
  },
  "releaseYear": 2024,
  "screens": [
    {
      "id": "cover",
      "label": "Cover",
      "diagonalInch": 6.3,
      "resolutionPx": {
        "width": 1080,
        "height": 2424
      },
      "logicalSizePx": {
        "width": 1080,
        "height": 2424
      },
      "captureOrientation": "portrait",
      "captureRotation": 0,
      "ppi": 422,
      "logicalSizeDp": {
        "width": 443.08,
        "height": 994.46
      },
      "densityDpi": 390,
      "cornerRadiiDp": {
        "topLeft": 47.18,
        "topRight": 47.18,
        "bottomRight": 47.18,
        "bottomLeft": 47.18
      },
      "cornerRadiiPx": {
        "topLeft": 115,
        "topRight": 115,
        "bottomRight": 115,
        "bottomLeft": 115
      },
      "insets": {
        "gesture": {
          "systemBars": {
            "top": 62.36,
            "right": 0,
            "bottom": 24.21,
            "left": 0
          },
          "systemBarsPx": {
            "top": 152,
            "right": 0,
            "bottom": 59,
            "left": 0
          },
          "displayCutout": {
            "top": 62.36,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 152,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "cutoutShape": {
            "xDp": 198.56,
            "yDp": 8.21,
            "widthDp": 45.95,
            "heightDp": 54.15,
            "rightDp": 198.57,
            "bottomDp": 932.1,
            "xPx": 484,
            "yPx": 20,
            "widthPx": 112,
            "heightPx": 132,
            "rightPx": 484,
            "bottomPx": 2272
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_9_pro_fold device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Folded (device state CLOSED); no folding feature. Portrait rotation 0, default 390 dpi and font scale 1. InsetsProbe 1.5.0 reported a 1080×2424 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_9_pro_fold",
              "skin": "pixel_9_pro_fold",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9-pro-fold/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9_pro_fold profile, cover, gestures",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9-pro-fold/emulator-2026-09-27/cover-gesture.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        },
        "threeButton": {
          "systemBars": {
            "top": 62.36,
            "right": 0,
            "bottom": 48,
            "left": 0
          },
          "systemBarsPx": {
            "top": 152,
            "right": 0,
            "bottom": 117,
            "left": 0
          },
          "displayCutout": {
            "top": 62.36,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 152,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "cutoutShape": {
            "xDp": 198.56,
            "yDp": 8.21,
            "widthDp": 45.95,
            "heightDp": 54.15,
            "rightDp": 198.57,
            "bottomDp": 932.1,
            "xPx": 484,
            "yPx": 20,
            "widthPx": 112,
            "heightPx": 132,
            "rightPx": 484,
            "bottomPx": 2272
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_9_pro_fold device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Folded (device state CLOSED); no folding feature. Portrait rotation 0, default 390 dpi and font scale 1. InsetsProbe 1.5.0 reported a 1080×2424 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_9_pro_fold",
              "skin": "pixel_9_pro_fold",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9-pro-fold/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9_pro_fold profile, cover, 3-button",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9-pro-fold/emulator-2026-09-27/cover-threeButton.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        }
      },
      "sources": [
        {
          "kind": "official",
          "label": "Google Pixel phone hardware tech specs",
          "url": "https://support.google.com/pixelphone/answer/7158570?hl=en",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "official",
          "label": "AOSP Android Emulator skin pixel_9_pro_fold/closed (Apache 2.0)",
          "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_9_pro_fold/closed",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9_pro_fold profile, cover, gestures",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9-pro-fold/emulator-2026-09-27/cover-gesture.json",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9_pro_fold profile, cover, 3-button",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9-pro-fold/emulator-2026-09-27/cover-threeButton.json",
          "retrievedAt": "2026-09-27"
        }
      ]
    },
    {
      "id": "main",
      "label": "Main",
      "diagonalInch": 8.0,
      "resolutionPx": {
        "width": 2076,
        "height": 2152
      },
      "logicalSizePx": {
        "width": 2076,
        "height": 2152
      },
      "captureOrientation": "portrait",
      "captureRotation": 0,
      "ppi": 373,
      "logicalSizeDp": {
        "width": 851.69,
        "height": 882.87
      },
      "densityDpi": 390,
      "cornerRadiiDp": {
        "topLeft": 34.87,
        "topRight": 34.87,
        "bottomRight": 34.87,
        "bottomLeft": 34.87
      },
      "cornerRadiiPx": {
        "topLeft": 85,
        "topRight": 85,
        "bottomRight": 85,
        "bottomLeft": 85
      },
      "insets": {
        "gesture": {
          "systemBars": {
            "top": 55.79,
            "right": 0,
            "bottom": 32,
            "left": 0
          },
          "systemBarsPx": {
            "top": 136,
            "right": 0,
            "bottom": 78,
            "left": 0
          },
          "displayCutout": {
            "top": 55.79,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 136,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "cutoutShape": {
            "xDp": 795.9,
            "yDp": 0,
            "widthDp": 55.79,
            "heightDp": 55.79,
            "rightDp": 0.0,
            "bottomDp": 827.08,
            "xPx": 1940,
            "yPx": 0,
            "widthPx": 136,
            "heightPx": 136,
            "rightPx": 0,
            "bottomPx": 2016
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_9_pro_fold device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Unfolded (device state OPENED); hinge 180° with a vertical FLAT folding feature. Portrait rotation 0, default 390 dpi and font scale 1. InsetsProbe 1.5.0 reported a 2076×2152 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_9_pro_fold",
              "skin": "pixel_9_pro_fold",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9-pro-fold/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9_pro_fold profile, inner display, gestures",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9-pro-fold/emulator-2026-09-27/main-gesture.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        },
        "threeButton": {
          "systemBars": {
            "top": 55.79,
            "right": 0,
            "bottom": 56.21,
            "left": 0
          },
          "systemBarsPx": {
            "top": 136,
            "right": 0,
            "bottom": 137,
            "left": 0
          },
          "displayCutout": {
            "top": 55.79,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 136,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "cutoutShape": {
            "xDp": 795.9,
            "yDp": 0,
            "widthDp": 55.79,
            "heightDp": 55.79,
            "rightDp": 0.0,
            "bottomDp": 827.08,
            "xPx": 1940,
            "yPx": 0,
            "widthPx": 136,
            "heightPx": 136,
            "rightPx": 0,
            "bottomPx": 2016
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_9_pro_fold device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Unfolded (device state OPENED); hinge 180° with a vertical FLAT folding feature. Portrait rotation 0, default 390 dpi and font scale 1. InsetsProbe 1.5.0 reported a 2076×2152 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_9_pro_fold",
              "skin": "pixel_9_pro_fold",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9-pro-fold/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9_pro_fold profile, inner display, 3-button",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9-pro-fold/emulator-2026-09-27/main-threeButton.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        }
      },
      "sources": [
        {
          "kind": "official",
          "label": "Google Pixel phone hardware tech specs",
          "url": "https://support.google.com/pixelphone/answer/7158570?hl=en",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "official",
          "label": "AOSP Android Emulator skin pixel_9_pro_fold/default (Apache 2.0)",
          "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_9_pro_fold/default",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9_pro_fold profile, inner display, gestures",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9-pro-fold/emulator-2026-09-27/main-gesture.json",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9_pro_fold profile, inner display, 3-button",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9-pro-fold/emulator-2026-09-27/main-threeButton.json",
          "retrievedAt": "2026-09-27"
        }
      ]
    }
  ],
  "sources": [
    {
      "kind": "official",
      "label": "Google Pixel phone hardware tech specs",
      "url": "https://support.google.com/pixelphone/answer/7158570?hl=en",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "official",
      "label": "AOSP Android Emulator skin pixel_9_pro_fold/closed (Apache 2.0)",
      "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_9_pro_fold/closed",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9_pro_fold profile, cover, gestures",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9-pro-fold/emulator-2026-09-27/cover-gesture.json",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9_pro_fold profile, cover, 3-button",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9-pro-fold/emulator-2026-09-27/cover-threeButton.json",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "official",
      "label": "AOSP Android Emulator skin pixel_9_pro_fold/default (Apache 2.0)",
      "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_9_pro_fold/default",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9_pro_fold profile, inner display, gestures",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9-pro-fold/emulator-2026-09-27/main-gesture.json",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9_pro_fold profile, inner display, 3-button",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9-pro-fold/emulator-2026-09-27/main-threeButton.json",
      "retrievedAt": "2026-09-27"
    }
  ]
};
