// Generated by scripts/import-emulator-captures.py from the raw emulator captures.
import type { Device } from "../../types";

export const pixel7Pro: Device = {
  "slug": "pixel-7-pro",
  "name": "Pixel 7 Pro",
  "brand": "Google",
  "series": "Pixel",
  "formFactor": "bar",
  "releaseYear": 2022,
  "screens": [
    {
      "id": "main",
      "label": "Main",
      "diagonalInch": 6.7,
      "resolutionPx": {
        "width": 1440,
        "height": 3120
      },
      "logicalSizePx": {
        "width": 1440,
        "height": 3120
      },
      "captureOrientation": "portrait",
      "captureRotation": 0,
      "ppi": 512,
      "logicalSizeDp": {
        "width": 411.43,
        "height": 891.43
      },
      "densityDpi": 560,
      "cornerRadiiDp": {
        "topLeft": 14.29,
        "topRight": 14.29,
        "bottomRight": 14,
        "bottomLeft": 14
      },
      "cornerRadiiPx": {
        "topLeft": 50,
        "topRight": 50,
        "bottomRight": 49,
        "bottomLeft": 49
      },
      "insets": {
        "gesture": {
          "systemBars": {
            "top": 41.14,
            "right": 0,
            "bottom": 24,
            "left": 0
          },
          "systemBarsPx": {
            "top": 144,
            "right": 0,
            "bottom": 84,
            "left": 0
          },
          "displayCutout": {
            "top": 41.14,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 144,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "cutoutShape": {
            "xDp": 186.57,
            "yDp": 0,
            "widthDp": 41.43,
            "heightDp": 41.14,
            "rightDp": 183.43,
            "bottomDp": 850.29,
            "xPx": 653,
            "yPx": 0,
            "widthPx": 145,
            "heightPx": 144,
            "rightPx": 642,
            "bottomPx": 2976
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_7_pro device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Portrait rotation 0, default 560 dpi and font scale 1. InsetsProbe 1.5.0 reported a 1440×3120 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_7_pro",
              "skin": "pixel_7_pro",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-7-pro/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_7_pro profile, gestures",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-7-pro/emulator-2026-09-27/main-gesture.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        },
        "threeButton": {
          "systemBars": {
            "top": 41.14,
            "right": 0,
            "bottom": 48,
            "left": 0
          },
          "systemBarsPx": {
            "top": 144,
            "right": 0,
            "bottom": 168,
            "left": 0
          },
          "displayCutout": {
            "top": 41.14,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 144,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "cutoutShape": {
            "xDp": 186.57,
            "yDp": 0,
            "widthDp": 41.43,
            "heightDp": 41.14,
            "rightDp": 183.43,
            "bottomDp": 850.29,
            "xPx": 653,
            "yPx": 0,
            "widthPx": 145,
            "heightPx": 144,
            "rightPx": 642,
            "bottomPx": 2976
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_7_pro device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Portrait rotation 0, default 560 dpi and font scale 1. InsetsProbe 1.5.0 reported a 1440×3120 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_7_pro",
              "skin": "pixel_7_pro",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-7-pro/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_7_pro profile, 3-button",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-7-pro/emulator-2026-09-27/main-threeButton.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        }
      },
      "sources": [
        {
          "kind": "official",
          "label": "Google Pixel phone hardware tech specs",
          "url": "https://support.google.com/pixelphone/answer/7158570?hl=en",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "official",
          "label": "AOSP Android Emulator skin pixel_7_pro (Apache 2.0)",
          "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_7_pro",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_7_pro profile, gestures",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-7-pro/emulator-2026-09-27/main-gesture.json",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_7_pro profile, 3-button",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-7-pro/emulator-2026-09-27/main-threeButton.json",
          "retrievedAt": "2026-09-27"
        }
      ]
    }
  ],
  "sources": [
    {
      "kind": "official",
      "label": "Google Pixel phone hardware tech specs",
      "url": "https://support.google.com/pixelphone/answer/7158570?hl=en",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "official",
      "label": "AOSP Android Emulator skin pixel_7_pro (Apache 2.0)",
      "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_7_pro",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_7_pro profile, gestures",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-7-pro/emulator-2026-09-27/main-gesture.json",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_7_pro profile, 3-button",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-7-pro/emulator-2026-09-27/main-threeButton.json",
      "retrievedAt": "2026-09-27"
    }
  ]
};
