// Generated by scripts/import-emulator-captures.py from the raw emulator captures.
import type { Device } from "../../types";

export const pixelFold: Device = {
  "slug": "pixel-fold",
  "name": "Pixel Fold",
  "brand": "Google",
  "series": "Pixel Fold",
  "formFactor": "foldable-book",
  "chassisMm": {
    "unfoldedWidth": 158.7,
    "unfoldedDepth": 5.8,
    "foldedDepth": 12.1,
    "source": {
      "kind": "official",
      "label": "Google Pixel phone hardware tech specs",
      "url": "https://support.google.com/pixelphone/answer/7158570?hl=en",
      "retrievedAt": "2026-09-27"
    }
  },
  "releaseYear": 2023,
  "screens": [
    {
      "id": "cover",
      "label": "Cover",
      "diagonalInch": 5.8,
      "resolutionPx": {
        "width": 1080,
        "height": 2092
      },
      "logicalSizePx": {
        "width": 1080,
        "height": 2092
      },
      "captureOrientation": "portrait",
      "captureRotation": 0,
      "ppi": 408,
      "logicalSizeDp": {
        "width": 411.43,
        "height": 796.95
      },
      "densityDpi": 420,
      "cornerRadiiDp": null,
      "cornerRadiiPx": null,
      "insets": {
        "gesture": {
          "systemBars": {
            "top": 41.9,
            "right": 0,
            "bottom": 24,
            "left": 0
          },
          "systemBarsPx": {
            "top": 110,
            "right": 0,
            "bottom": 63,
            "left": 0
          },
          "displayCutout": {
            "top": 41.9,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 110,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "cutoutShape": {
            "xDp": 182.86,
            "yDp": 0,
            "widthDp": 41.9,
            "heightDp": 41.9,
            "rightDp": 186.67,
            "bottomDp": 755.05,
            "xPx": 480,
            "yPx": 0,
            "widthPx": 110,
            "heightPx": 110,
            "rightPx": 490,
            "bottomPx": 1982
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_fold device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Folded (device state CLOSED); no folding feature. Portrait rotation 0, default 420 dpi and font scale 1. InsetsProbe 1.5.0 reported a 1080×2092 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_fold",
              "skin": "pixel_fold",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-fold/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_fold profile, cover, gestures",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-fold/emulator-2026-09-27/cover-gesture.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        },
        "threeButton": {
          "systemBars": {
            "top": 41.9,
            "right": 0,
            "bottom": 48,
            "left": 0
          },
          "systemBarsPx": {
            "top": 110,
            "right": 0,
            "bottom": 126,
            "left": 0
          },
          "displayCutout": {
            "top": 41.9,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 110,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "cutoutShape": {
            "xDp": 182.86,
            "yDp": 0,
            "widthDp": 41.9,
            "heightDp": 41.9,
            "rightDp": 186.67,
            "bottomDp": 755.05,
            "xPx": 480,
            "yPx": 0,
            "widthPx": 110,
            "heightPx": 110,
            "rightPx": 490,
            "bottomPx": 1982
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_fold device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Folded (device state CLOSED); no folding feature. Portrait rotation 0, default 420 dpi and font scale 1. InsetsProbe 1.5.0 reported a 1080×2092 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_fold",
              "skin": "pixel_fold",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-fold/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_fold profile, cover, 3-button",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-fold/emulator-2026-09-27/cover-threeButton.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        }
      },
      "sources": [
        {
          "kind": "official",
          "label": "Google Pixel phone hardware tech specs",
          "url": "https://support.google.com/pixelphone/answer/7158570?hl=en",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "official",
          "label": "AOSP Android Emulator skin pixel_fold/closed (Apache 2.0)",
          "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_fold/closed",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_fold profile, cover, gestures",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-fold/emulator-2026-09-27/cover-gesture.json",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_fold profile, cover, 3-button",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-fold/emulator-2026-09-27/cover-threeButton.json",
          "retrievedAt": "2026-09-27"
        }
      ]
    },
    {
      "id": "main",
      "label": "Main",
      "diagonalInch": 7.6,
      "resolutionPx": {
        "width": 2208,
        "height": 1840
      },
      "logicalSizePx": {
        "width": 2208,
        "height": 1840
      },
      "captureOrientation": "landscape",
      "captureRotation": 0,
      "ppi": 380,
      "logicalSizeDp": {
        "width": 841.14,
        "height": 700.95
      },
      "densityDpi": 420,
      "cornerRadiiDp": null,
      "cornerRadiiPx": null,
      "insets": {
        "gesture": {
          "systemBars": {
            "top": 28.19,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "systemBarsPx": {
            "top": 74,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutout": {
            "top": 0,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 0,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_fold device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Unfolded (device state OPENED); hinge 180° with a vertical FLAT folding feature. Landscape rotation 0, default 420 dpi and font scale 1. InsetsProbe 1.5.0 reported a 2208×1840 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_fold",
              "skin": "pixel_fold",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-fold/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_fold profile, inner display, gestures",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-fold/emulator-2026-09-27/main-gesture.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        },
        "threeButton": {
          "systemBars": {
            "top": 28.19,
            "right": 0,
            "bottom": 56,
            "left": 0
          },
          "systemBarsPx": {
            "top": 74,
            "right": 0,
            "bottom": 147,
            "left": 0
          },
          "displayCutout": {
            "top": 0,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 0,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_fold device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Unfolded (device state OPENED); hinge 180° with a vertical FLAT folding feature. Landscape rotation 0, default 420 dpi and font scale 1. InsetsProbe 1.5.0 reported a 2208×1840 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_fold",
              "skin": "pixel_fold",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-fold/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_fold profile, inner display, 3-button",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-fold/emulator-2026-09-27/main-threeButton.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        }
      },
      "sources": [
        {
          "kind": "official",
          "label": "Google Pixel phone hardware tech specs",
          "url": "https://support.google.com/pixelphone/answer/7158570?hl=en",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "official",
          "label": "AOSP Android Emulator skin pixel_fold/default (Apache 2.0)",
          "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_fold/default",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_fold profile, inner display, gestures",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-fold/emulator-2026-09-27/main-gesture.json",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_fold profile, inner display, 3-button",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-fold/emulator-2026-09-27/main-threeButton.json",
          "retrievedAt": "2026-09-27"
        }
      ]
    }
  ],
  "sources": [
    {
      "kind": "official",
      "label": "Google Pixel phone hardware tech specs",
      "url": "https://support.google.com/pixelphone/answer/7158570?hl=en",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "official",
      "label": "AOSP Android Emulator skin pixel_fold/closed (Apache 2.0)",
      "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_fold/closed",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_fold profile, cover, gestures",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-fold/emulator-2026-09-27/cover-gesture.json",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_fold profile, cover, 3-button",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-fold/emulator-2026-09-27/cover-threeButton.json",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "official",
      "label": "AOSP Android Emulator skin pixel_fold/default (Apache 2.0)",
      "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_fold/default",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_fold profile, inner display, gestures",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-fold/emulator-2026-09-27/main-gesture.json",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_fold profile, inner display, 3-button",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-fold/emulator-2026-09-27/main-threeButton.json",
      "retrievedAt": "2026-09-27"
    }
  ]
};
