// Generated by scripts/import-emulator-captures.py. AOSP emulator artwork, Apache 2.0;
// provenance per asset in public/skins/<slug>/<screen>/source.json.
import type { DeviceSkin } from "./skins";

export const aospSkins: Record<string, DeviceSkin> = {
  "pixel-10-pro-fold/cover": {
    "image": "/skins/pixel-10-pro-fold/cover/back.webp",
    "foreground": "/skins/pixel-10-pro-fold/cover/mask.webp",
    "width": 1236,
    "height": 2495,
    "screen": {
      "x": 84,
      "y": 66,
      "width": 1080,
      "height": 2364
    },
    "body": {
      "x": 1,
      "y": 0,
      "width": 1235,
      "height": 2495,
      "radius": 133
    }
  },
  "pixel-10-pro-fold/main": {
    "image": "/skins/pixel-10-pro-fold/main/back.webp",
    "foreground": "/skins/pixel-10-pro-fold/main/mask.webp",
    "width": 2201,
    "height": 2268,
    "screen": {
      "x": 62,
      "y": 58,
      "width": 2076,
      "height": 2152
    },
    "body": {
      "x": 0,
      "y": 25,
      "width": 2201,
      "height": 2218,
      "radius": 95
    }
  },
  "pixel-9-pro-fold/cover": {
    "image": "/skins/pixel-9-pro-fold/cover/back.webp",
    "foreground": "/skins/pixel-9-pro-fold/cover/mask.webp",
    "width": 1236,
    "height": 2554,
    "screen": {
      "x": 94,
      "y": 70,
      "width": 1080,
      "height": 2424
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1236,
      "height": 2554,
      "radius": 44
    }
  },
  "pixel-9-pro-fold/main": {
    "image": "/skins/pixel-9-pro-fold/main/back.webp",
    "foreground": "/skins/pixel-9-pro-fold/main/mask.webp",
    "width": 2204,
    "height": 2274,
    "screen": {
      "x": 62,
      "y": 62,
      "width": 2076,
      "height": 2152
    },
    "body": {
      "x": 0,
      "y": 18,
      "width": 2204,
      "height": 2238,
      "radius": 110
    }
  },
  "pixel-fold/cover": {
    "image": "/skins/pixel-fold/cover/back.webp",
    "foreground": "/skins/pixel-fold/cover/mask.webp",
    "width": 1268,
    "height": 2233,
    "screen": {
      "x": 116,
      "y": 73,
      "width": 1080,
      "height": 2092
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1267,
      "height": 2233,
      "radius": 36
    }
  },
  "pixel-fold/main": {
    "image": "/skins/pixel-fold/main/back.webp",
    "foreground": "/skins/pixel-fold/main/mask.webp",
    "width": 2368,
    "height": 2087,
    "screen": {
      "x": 77,
      "y": 126,
      "width": 2208,
      "height": 1840
    },
    "body": {
      "x": 0,
      "y": 24,
      "width": 2368,
      "height": 2038,
      "radius": 60
    }
  },
  "pixel-10a/main": {
    "image": "/skins/pixel-10a/main/back.webp",
    "foreground": "/skins/pixel-10a/main/mask.webp",
    "width": 1218,
    "height": 2553,
    "screen": {
      "x": 65,
      "y": 64,
      "width": 1080,
      "height": 2424
    },
    "body": {
      "x": 1,
      "y": 1,
      "width": 1216,
      "height": 2550,
      "radius": 208
    }
  },
  "pixel-10-pro-xl/main": {
    "image": "/skins/pixel-10-pro-xl/main/back.webp",
    "foreground": "/skins/pixel-10-pro-xl/main/mask.webp",
    "width": 1472,
    "height": 3111,
    "screen": {
      "x": 60,
      "y": 55,
      "width": 1344,
      "height": 2992
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1472,
      "height": 3101,
      "radius": 225
    }
  },
  "pixel-10-pro/main": {
    "image": "/skins/pixel-10-pro/main/back.webp",
    "foreground": "/skins/pixel-10-pro/main/mask.webp",
    "width": 1410,
    "height": 2968,
    "screen": {
      "x": 59,
      "y": 60,
      "width": 1280,
      "height": 2856
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1410,
      "height": 2968,
      "radius": 269
    }
  },
  "pixel-10/main": {
    "image": "/skins/pixel-10/main/back.webp",
    "foreground": "/skins/pixel-10/main/mask.webp",
    "width": 1205,
    "height": 2535,
    "screen": {
      "x": 59,
      "y": 55,
      "width": 1080,
      "height": 2424
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1205,
      "height": 2535,
      "radius": 218
    }
  },
  "pixel-9-pro-xl/main": {
    "image": "/skins/pixel-9-pro-xl/main/back.webp",
    "foreground": "/skins/pixel-9-pro-xl/main/mask.webp",
    "width": 1466,
    "height": 3101,
    "screen": {
      "x": 57,
      "y": 56,
      "width": 1344,
      "height": 2992
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1466,
      "height": 3100,
      "radius": 251
    }
  },
  "pixel-9-pro/main": {
    "image": "/skins/pixel-9-pro/main/back.webp",
    "foreground": "/skins/pixel-9-pro/main/mask.webp",
    "width": 1408,
    "height": 2974,
    "screen": {
      "x": 60,
      "y": 61,
      "width": 1280,
      "height": 2856
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1408,
      "height": 2974,
      "radius": 258
    }
  },
  "pixel-9/main": {
    "image": "/skins/pixel-9/main/back.webp",
    "foreground": "/skins/pixel-9/main/mask.webp",
    "width": 1198,
    "height": 2531,
    "screen": {
      "x": 55,
      "y": 58,
      "width": 1080,
      "height": 2424
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1198,
      "height": 2531,
      "radius": 221
    }
  },
  "pixel-9a/main": {
    "image": "/skins/pixel-9a/main/back.webp",
    "foreground": "/skins/pixel-9a/main/mask.webp",
    "width": 1224,
    "height": 2570,
    "screen": {
      "x": 69,
      "y": 73,
      "width": 1080,
      "height": 2424
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1224,
      "height": 2570,
      "radius": 225
    }
  },
  "pixel-8-pro/main": {
    "image": "/skins/pixel-8-pro/main/back.webp",
    "foreground": "/skins/pixel-8-pro/main/mask.webp",
    "width": 1469,
    "height": 3104,
    "screen": {
      "x": 58,
      "y": 58,
      "width": 1344,
      "height": 2992
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1469,
      "height": 3104,
      "radius": 150
    }
  },
  "pixel-8/main": {
    "image": "/skins/pixel-8/main/back.webp",
    "foreground": "/skins/pixel-8/main/mask.webp",
    "width": 1187,
    "height": 2513,
    "screen": {
      "x": 49,
      "y": 55,
      "width": 1080,
      "height": 2400
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1187,
      "height": 2513,
      "radius": 161
    }
  },
  "pixel-8a/main": {
    "image": "/skins/pixel-8a/main/back.webp",
    "foreground": "/skins/pixel-8a/main/mask.webp",
    "width": 1198,
    "height": 2539,
    "screen": {
      "x": 57,
      "y": 57,
      "width": 1080,
      "height": 2400
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1197,
      "height": 2538,
      "radius": 106
    }
  },
  "pixel-7-pro/main": {
    "image": "/skins/pixel-7-pro/main/back.webp",
    "foreground": "/skins/pixel-7-pro/main/mask.webp",
    "width": 1547,
    "height": 3272,
    "screen": {
      "x": 48,
      "y": 66,
      "width": 1440,
      "height": 3120
    },
    "body": {
      "x": 0,
      "y": 1,
      "width": 1546,
      "height": 3268,
      "radius": 127
    }
  },
  "pixel-7/main": {
    "image": "/skins/pixel-7/main/back.webp",
    "foreground": "/skins/pixel-7/main/mask.webp",
    "width": 1200,
    "height": 2541,
    "screen": {
      "x": 59,
      "y": 58,
      "width": 1080,
      "height": 2400
    },
    "body": {
      "x": 1,
      "y": 1,
      "width": 1198,
      "height": 2539,
      "radius": 104
    }
  },
  "pixel-7a/main": {
    "image": "/skins/pixel-7a/main/back.webp",
    "foreground": "/skins/pixel-7a/main/mask.webp",
    "width": 1226,
    "height": 2559,
    "screen": {
      "x": 69,
      "y": 69,
      "width": 1080,
      "height": 2400
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1226,
      "height": 2559,
      "radius": 87
    }
  },
  "pixel-6-pro/main": {
    "image": "/skins/pixel-6-pro/main/back.webp",
    "foreground": "/skins/pixel-6-pro/main/mask.webp",
    "width": 1527,
    "height": 3289,
    "screen": {
      "x": 41,
      "y": 72,
      "width": 1440,
      "height": 3120
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1527,
      "height": 3289,
      "radius": 97
    }
  },
  "pixel-6/main": {
    "image": "/skins/pixel-6/main/back.webp",
    "foreground": "/skins/pixel-6/main/mask.webp",
    "width": 1209,
    "height": 2553,
    "screen": {
      "x": 60,
      "y": 69,
      "width": 1080,
      "height": 2400
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1203,
      "height": 2553,
      "radius": 76
    }
  },
  "pixel-6a/main": {
    "image": "/skins/pixel-6a/main/back.webp",
    "foreground": "/skins/pixel-6a/main/mask.webp",
    "width": 1207,
    "height": 2555,
    "screen": {
      "x": 57,
      "y": 69,
      "width": 1080,
      "height": 2400
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1202,
      "height": 2555,
      "radius": 81
    }
  },
  "pixel-5/main": {
    "image": "/skins/pixel-5/main/back.webp",
    "foreground": "/skins/pixel-5/main/mask.webp",
    "width": 1211,
    "height": 2474,
    "screen": {
      "x": 60,
      "y": 65,
      "width": 1080,
      "height": 2340
    },
    "body": {
      "x": 1,
      "y": 0,
      "width": 1208,
      "height": 2474,
      "radius": 234
    }
  },
  "pixel-4a/main": {
    "image": "/skins/pixel-4a/main/back.webp",
    "foreground": "/skins/pixel-4a/main/mask.webp",
    "width": 1204,
    "height": 2491,
    "screen": {
      "x": 62,
      "y": 68,
      "width": 1080,
      "height": 2340
    },
    "body": {
      "x": 1,
      "y": 2,
      "width": 1195,
      "height": 2487,
      "radius": 138
    }
  },
  "pixel-tablet/main": {
    "image": "/skins/pixel-tablet/main/back.webp",
    "foreground": "/skins/pixel-tablet/main/mask.webp",
    "width": 2798,
    "height": 1837,
    "screen": {
      "x": 119,
      "y": 117,
      "width": 2560,
      "height": 1600
    },
    "body": {
      "x": 0,
      "y": 1,
      "width": 2797,
      "height": 1835,
      "radius": 125
    }
  }
};
