// Generated by scripts/import-emulator-captures.py. AOSP emulator artwork, Apache 2.0;
// provenance per asset in public/skins/<slug>/<screen>/source.json.
import type { DeviceSkin } from "./skins";

export const aospSkins: Record<string, DeviceSkin> = {
  "pixel-10-pro-fold/cover": {
    "image": "/skins/pixel-10-pro-fold/cover/back.webp",
    "foreground": "/skins/pixel-10-pro-fold/cover/mask.webp",
    "width": 1236,
    "height": 2495,
    "screen": {
      "x": 84,
      "y": 66,
      "width": 1080,
      "height": 2364
    },
    "body": {
      "x": 1,
      "y": 0,
      "width": 1235,
      "height": 2495,
      "radius": 133
    }
  },
  "pixel-10-pro-fold/main": {
    "image": "/skins/pixel-10-pro-fold/main/back.webp",
    "foreground": "/skins/pixel-10-pro-fold/main/mask.webp",
    "width": 2201,
    "height": 2268,
    "screen": {
      "x": 62,
      "y": 58,
      "width": 2076,
      "height": 2152
    },
    "body": {
      "x": 0,
      "y": 25,
      "width": 2201,
      "height": 2218,
      "radius": 95
    }
  },
  "pixel-9-pro-fold/cover": {
    "image": "/skins/pixel-9-pro-fold/cover/back.webp",
    "foreground": "/skins/pixel-9-pro-fold/cover/mask.webp",
    "width": 1236,
    "height": 2554,
    "screen": {
      "x": 94,
      "y": 70,
      "width": 1080,
      "height": 2424
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1236,
      "height": 2554,
      "radius": 44
    }
  },
  "pixel-9-pro-fold/main": {
    "image": "/skins/pixel-9-pro-fold/main/back.webp",
    "foreground": "/skins/pixel-9-pro-fold/main/mask.webp",
    "width": 2204,
    "height": 2274,
    "screen": {
      "x": 62,
      "y": 62,
      "width": 2076,
      "height": 2152
    },
    "body": {
      "x": 0,
      "y": 18,
      "width": 2204,
      "height": 2238,
      "radius": 110
    }
  },
  "pixel-fold/cover": {
    "image": "/skins/pixel-fold/cover/back.webp",
    "foreground": "/skins/pixel-fold/cover/mask.webp",
    "width": 1268,
    "height": 2233,
    "screen": {
      "x": 116,
      "y": 73,
      "width": 1080,
      "height": 2092
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1267,
      "height": 2233,
      "radius": 36
    }
  },
  "pixel-fold/main": {
    "image": "/skins/pixel-fold/main/back.webp",
    "foreground": "/skins/pixel-fold/main/mask.webp",
    "width": 2368,
    "height": 2087,
    "screen": {
      "x": 77,
      "y": 126,
      "width": 2208,
      "height": 1840
    },
    "body": {
      "x": 0,
      "y": 24,
      "width": 2368,
      "height": 2038,
      "radius": 60
    }
  },
  "pixel-10-pro/main": {
    "image": "/skins/pixel-10-pro/main/back.webp",
    "foreground": "/skins/pixel-10-pro/main/mask.webp",
    "width": 1410,
    "height": 2968,
    "screen": {
      "x": 59,
      "y": 60,
      "width": 1280,
      "height": 2856
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1410,
      "height": 2968,
      "radius": 269
    }
  },
  "pixel-10/main": {
    "image": "/skins/pixel-10/main/back.webp",
    "foreground": "/skins/pixel-10/main/mask.webp",
    "width": 1205,
    "height": 2535,
    "screen": {
      "x": 59,
      "y": 55,
      "width": 1080,
      "height": 2424
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1205,
      "height": 2535,
      "radius": 218
    }
  },
  "pixel-9-pro-xl/main": {
    "image": "/skins/pixel-9-pro-xl/main/back.webp",
    "foreground": "/skins/pixel-9-pro-xl/main/mask.webp",
    "width": 1466,
    "height": 3101,
    "screen": {
      "x": 57,
      "y": 56,
      "width": 1344,
      "height": 2992
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1466,
      "height": 3100,
      "radius": 251
    }
  },
  "pixel-9-pro/main": {
    "image": "/skins/pixel-9-pro/main/back.webp",
    "foreground": "/skins/pixel-9-pro/main/mask.webp",
    "width": 1408,
    "height": 2974,
    "screen": {
      "x": 60,
      "y": 61,
      "width": 1280,
      "height": 2856
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1408,
      "height": 2974,
      "radius": 258
    }
  },
  "pixel-9/main": {
    "image": "/skins/pixel-9/main/back.webp",
    "foreground": "/skins/pixel-9/main/mask.webp",
    "width": 1198,
    "height": 2531,
    "screen": {
      "x": 55,
      "y": 58,
      "width": 1080,
      "height": 2424
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1198,
      "height": 2531,
      "radius": 221
    }
  },
  "pixel-9a/main": {
    "image": "/skins/pixel-9a/main/back.webp",
    "foreground": "/skins/pixel-9a/main/mask.webp",
    "width": 1224,
    "height": 2570,
    "screen": {
      "x": 69,
      "y": 73,
      "width": 1080,
      "height": 2424
    },
    "body": {
      "x": 0,
      "y": 0,
      "width": 1224,
      "height": 2570,
      "radius": 225
    }
  },
  "pixel-tablet/main": {
    "image": "/skins/pixel-tablet/main/back.webp",
    "foreground": "/skins/pixel-tablet/main/mask.webp",
    "width": 2798,
    "height": 1837,
    "screen": {
      "x": 119,
      "y": 117,
      "width": 2560,
      "height": 1600
    },
    "body": {
      "x": 0,
      "y": 1,
      "width": 2797,
      "height": 1835,
      "radius": 125
    }
  }
};
