import data from "./changelog.json";
import { REPO_URL } from "./site";

/** Generated by scripts/generate-changelog.mjs from data commits; never edited by hand. */
export interface ChangelogEntry {
  hash: string;
  date: string;
  /** "data": measurement commits; "site": merged pull requests and direct site changes. */
  area: "data" | "site";
  kind: "added" | "corrected";
  summary: string;
  devices: string[];
  /** Pull request number for merged site work. */
  pr?: number;
}

export const changelog = data.entries as ChangelogEntry[];
export const CHANGELOG_PATH = "/changelog";
export const CHANGELOG_FEED_PATH = "/changelog.xml";

export const commitUrl = (hash: string) => `${REPO_URL}/commit/${hash}`;
export const pullUrl = (pr: number) => `${REPO_URL}/pull/${pr}`;
export const areaLabel = (entry: ChangelogEntry) => entry.area === "site" ? "Site" : "Data";
/** Pull request page for merged site work, otherwise the commit. */
export const entryUrl = (entry: ChangelogEntry) => entry.pr ? pullUrl(entry.pr) : commitUrl(entry.hash);

