// Generated by scripts/import-emulator-captures.py from the raw emulator captures.
import type { Device } from "../../types";

export const pixel9a: Device = {
  "slug": "pixel-9a",
  "name": "Pixel 9a",
  "brand": "Google",
  "series": "Pixel",
  "formFactor": "bar",
  "releaseYear": 2025,
  "screens": [
    {
      "id": "main",
      "label": "Main",
      "diagonalInch": 6.3,
      "resolutionPx": {
        "width": 1080,
        "height": 2424
      },
      "logicalSizePx": {
        "width": 1080,
        "height": 2424
      },
      "captureOrientation": "portrait",
      "captureRotation": 0,
      "ppi": 422,
      "logicalSizeDp": {
        "width": 411.43,
        "height": 923.43
      },
      "densityDpi": 420,
      "cornerRadiiDp": {
        "topLeft": 50.29,
        "topRight": 50.29,
        "bottomRight": 50.29,
        "bottomLeft": 50.29
      },
      "cornerRadiiPx": {
        "topLeft": 132,
        "topRight": 132,
        "bottomRight": 132,
        "bottomLeft": 132
      },
      "insets": {
        "gesture": {
          "systemBars": {
            "top": 54.1,
            "right": 0,
            "bottom": 24,
            "left": 0
          },
          "systemBarsPx": {
            "top": 142,
            "right": 0,
            "bottom": 63,
            "left": 0
          },
          "displayCutout": {
            "top": 54.1,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 142,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "cutoutShape": {
            "xDp": 184.76,
            "yDp": 0,
            "widthDp": 41.9,
            "heightDp": 54.1,
            "rightDp": 184.76,
            "bottomDp": 869.33,
            "xPx": 485,
            "yPx": 0,
            "widthPx": 110,
            "heightPx": 142,
            "rightPx": 485,
            "bottomPx": 2282
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_9a device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Portrait rotation 0, default 420 dpi and font scale 1. InsetsProbe 1.5.0 reported a 1080×2424 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_9a",
              "skin": "pixel_9a",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9a/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9a profile, gestures",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9a/emulator-2026-09-27/main-gesture.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        },
        "threeButton": {
          "systemBars": {
            "top": 54.1,
            "right": 0,
            "bottom": 48,
            "left": 0
          },
          "systemBarsPx": {
            "top": 142,
            "right": 0,
            "bottom": 126,
            "left": 0
          },
          "displayCutout": {
            "top": 54.1,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 142,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "cutoutShape": {
            "xDp": 184.76,
            "yDp": 0,
            "widthDp": 41.9,
            "heightDp": 54.1,
            "rightDp": 184.76,
            "bottomDp": 869.33,
            "xPx": 485,
            "yPx": 0,
            "widthPx": 110,
            "heightPx": 142,
            "rightPx": 485,
            "bottomPx": 2282
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_9a device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Portrait rotation 0, default 420 dpi and font scale 1. InsetsProbe 1.5.0 reported a 1080×2424 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_9a",
              "skin": "pixel_9a",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9a/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9a profile, 3-button",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9a/emulator-2026-09-27/main-threeButton.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        }
      },
      "sources": [
        {
          "kind": "official",
          "label": "Google Pixel phone hardware tech specs",
          "url": "https://support.google.com/pixelphone/answer/7158570?hl=en",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "official",
          "label": "AOSP Android Emulator skin pixel_9a (Apache 2.0)",
          "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_9a",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9a profile, gestures",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9a/emulator-2026-09-27/main-gesture.json",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9a profile, 3-button",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9a/emulator-2026-09-27/main-threeButton.json",
          "retrievedAt": "2026-09-27"
        }
      ]
    }
  ],
  "sources": [
    {
      "kind": "official",
      "label": "Google Pixel phone hardware tech specs",
      "url": "https://support.google.com/pixelphone/answer/7158570?hl=en",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "official",
      "label": "AOSP Android Emulator skin pixel_9a (Apache 2.0)",
      "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_9a",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9a profile, gestures",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9a/emulator-2026-09-27/main-gesture.json",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_9a profile, 3-button",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-9a/emulator-2026-09-27/main-threeButton.json",
      "retrievedAt": "2026-09-27"
    }
  ]
};
