// Generated by scripts/import-emulator-captures.py from the raw emulator captures.
import type { Device } from "../../types";

export const pixelTablet: Device = {
  "slug": "pixel-tablet",
  "name": "Pixel Tablet",
  "brand": "Google",
  "series": "Pixel Tablet",
  "formFactor": "tablet",
  "releaseYear": 2023,
  "screens": [
    {
      "id": "main",
      "label": "Main",
      "diagonalInch": 10.95,
      "resolutionPx": {
        "width": 2560,
        "height": 1600
      },
      "logicalSizePx": {
        "width": 2560,
        "height": 1600
      },
      "captureOrientation": "landscape",
      "captureRotation": 0,
      "ppi": 276,
      "logicalSizeDp": {
        "width": 1280,
        "height": 800
      },
      "densityDpi": 320,
      "cornerRadiiDp": null,
      "cornerRadiiPx": null,
      "insets": {
        "gesture": {
          "systemBars": {
            "top": 24,
            "right": 0,
            "bottom": 32,
            "left": 0
          },
          "systemBarsPx": {
            "top": 48,
            "right": 0,
            "bottom": 64,
            "left": 0
          },
          "displayCutout": {
            "top": 0,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 0,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_tablet device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Landscape rotation 0, default 320 dpi and font scale 1. InsetsProbe 1.5.0 reported a 2560×1600 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_tablet",
              "skin": "pixel_tablet",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-tablet/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_tablet profile, gestures",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-tablet/emulator-2026-09-27/main-gesture.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        },
        "threeButton": {
          "systemBars": {
            "top": 24,
            "right": 0,
            "bottom": 56,
            "left": 0
          },
          "systemBarsPx": {
            "top": 48,
            "right": 0,
            "bottom": 112,
            "left": 0
          },
          "displayCutout": {
            "top": 0,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 0,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_tablet device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Landscape rotation 0, default 320 dpi and font scale 1. InsetsProbe 1.5.0 reported a 2560×1600 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_tablet",
              "skin": "pixel_tablet",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-tablet/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_tablet profile, 3-button",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-tablet/emulator-2026-09-27/main-threeButton.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        }
      },
      "sources": [
        {
          "kind": "official",
          "label": "Google Pixel Tablet hardware tech specs",
          "url": "https://support.google.com/googlepixeltablet/answer/13555146?hl=en",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "official",
          "label": "AOSP Android Emulator skin pixel_tablet (Apache 2.0)",
          "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_tablet",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_tablet profile, gestures",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-tablet/emulator-2026-09-27/main-gesture.json",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_tablet profile, 3-button",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-tablet/emulator-2026-09-27/main-threeButton.json",
          "retrievedAt": "2026-09-27"
        }
      ]
    }
  ],
  "sources": [
    {
      "kind": "official",
      "label": "Google Pixel Tablet hardware tech specs",
      "url": "https://support.google.com/googlepixeltablet/answer/13555146?hl=en",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "official",
      "label": "AOSP Android Emulator skin pixel_tablet (Apache 2.0)",
      "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_tablet",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_tablet profile, gestures",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-tablet/emulator-2026-09-27/main-gesture.json",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_tablet profile, 3-button",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel/pixel-tablet/emulator-2026-09-27/main-threeButton.json",
      "retrievedAt": "2026-09-27"
    }
  ]
};
