// Generated by scripts/import-emulator-captures.py from the raw emulator captures.
import type { Device } from "../../types";

export const pixel4a: Device = {
  "slug": "pixel-4a",
  "name": "Pixel 4a",
  "brand": "Google",
  "series": "Pixel",
  "formFactor": "bar",
  "releaseYear": 2020,
  "screens": [
    {
      "id": "main",
      "label": "Main",
      "diagonalInch": 5.8,
      "resolutionPx": {
        "width": 1080,
        "height": 2340
      },
      "logicalSizePx": {
        "width": 1080,
        "height": 2340
      },
      "captureOrientation": "portrait",
      "captureRotation": 0,
      "ppi": 443,
      "logicalSizeDp": {
        "width": 392.73,
        "height": 850.91
      },
      "densityDpi": 440,
      "cornerRadiiDp": null,
      "cornerRadiiPx": null,
      "insets": {
        "gesture": {
          "systemBars": {
            "top": 49.45,
            "right": 0,
            "bottom": 24,
            "left": 0
          },
          "systemBarsPx": {
            "top": 136,
            "right": 0,
            "bottom": 66,
            "left": 0
          },
          "displayCutout": {
            "top": 49.45,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 136,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "cutoutShape": {
            "xDp": 0,
            "yDp": 0,
            "widthDp": 49.45,
            "heightDp": 49.45,
            "rightDp": 343.28,
            "bottomDp": 801.46,
            "xPx": 0,
            "yPx": 0,
            "widthPx": 136,
            "heightPx": 136,
            "rightPx": 944,
            "bottomPx": 2204
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_4a device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Portrait rotation 0, default 440 dpi and font scale 1. InsetsProbe 1.5.0 reported a 1080×2340 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_4a",
              "skin": "pixel_4a",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-4a/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_4a profile, gestures",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-4a/emulator-2026-09-27/main-gesture.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        },
        "threeButton": {
          "systemBars": {
            "top": 49.45,
            "right": 0,
            "bottom": 48,
            "left": 0
          },
          "systemBarsPx": {
            "top": 136,
            "right": 0,
            "bottom": 132,
            "left": 0
          },
          "displayCutout": {
            "top": 49.45,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 136,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "cutoutShape": {
            "xDp": 0,
            "yDp": 0,
            "widthDp": 49.45,
            "heightDp": 49.45,
            "rightDp": 343.28,
            "bottomDp": 801.46,
            "xPx": 0,
            "yPx": 0,
            "widthPx": 136,
            "heightPx": 136,
            "rightPx": 944,
            "bottomPx": 2204
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_4a device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Portrait rotation 0, default 440 dpi and font scale 1. InsetsProbe 1.5.0 reported a 1080×2340 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_4a",
              "skin": "pixel_4a",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-4a/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_4a profile, 3-button",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-4a/emulator-2026-09-27/main-threeButton.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        }
      },
      "sources": [
        {
          "kind": "official",
          "label": "Google Pixel phone hardware tech specs (earlier models)",
          "url": "https://support.google.com/pixelphone/answer/16043605?hl=en",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "official",
          "label": "AOSP Android Emulator skin pixel_4a (Apache 2.0)",
          "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_4a",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_4a profile, gestures",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-4a/emulator-2026-09-27/main-gesture.json",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_4a profile, 3-button",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-4a/emulator-2026-09-27/main-threeButton.json",
          "retrievedAt": "2026-09-27"
        }
      ]
    }
  ],
  "sources": [
    {
      "kind": "official",
      "label": "Google Pixel phone hardware tech specs (earlier models)",
      "url": "https://support.google.com/pixelphone/answer/16043605?hl=en",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "official",
      "label": "AOSP Android Emulator skin pixel_4a (Apache 2.0)",
      "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_4a",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_4a profile, gestures",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-4a/emulator-2026-09-27/main-gesture.json",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_4a profile, 3-button",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-4a/emulator-2026-09-27/main-threeButton.json",
      "retrievedAt": "2026-09-27"
    }
  ]
};
