// Generated by scripts/import-emulator-captures.py from the raw emulator captures.
import type { Device } from "../../types";

export const pixel7: Device = {
  "slug": "pixel-7",
  "name": "Pixel 7",
  "brand": "Google",
  "series": "Pixel",
  "formFactor": "bar",
  "releaseYear": 2022,
  "screens": [
    {
      "id": "main",
      "label": "Main",
      "diagonalInch": 6.3,
      "resolutionPx": {
        "width": 1080,
        "height": 2400
      },
      "logicalSizePx": {
        "width": 1080,
        "height": 2400
      },
      "captureOrientation": "portrait",
      "captureRotation": 0,
      "ppi": 416,
      "logicalSizeDp": {
        "width": 411.43,
        "height": 914.29
      },
      "densityDpi": 420,
      "cornerRadiiDp": {
        "topLeft": 17.9,
        "topRight": 17.9,
        "bottomRight": 18.29,
        "bottomLeft": 18.29
      },
      "cornerRadiiPx": {
        "topLeft": 47,
        "topRight": 47,
        "bottomRight": 48,
        "bottomLeft": 48
      },
      "insets": {
        "gesture": {
          "systemBars": {
            "top": 51.81,
            "right": 0,
            "bottom": 24,
            "left": 0
          },
          "systemBarsPx": {
            "top": 136,
            "right": 0,
            "bottom": 63,
            "left": 0
          },
          "displayCutout": {
            "top": 51.81,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 136,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "cutoutShape": {
            "xDp": 182.86,
            "yDp": 0,
            "widthDp": 55.24,
            "heightDp": 51.81,
            "rightDp": 173.33,
            "bottomDp": 862.48,
            "xPx": 480,
            "yPx": 0,
            "widthPx": 145,
            "heightPx": 136,
            "rightPx": 455,
            "bottomPx": 2264
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_7 device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Portrait rotation 0, default 420 dpi and font scale 1. InsetsProbe 1.5.0 reported a 1080×2400 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_7",
              "skin": "pixel_7",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-7/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_7 profile, gestures",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-7/emulator-2026-09-27/main-gesture.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        },
        "threeButton": {
          "systemBars": {
            "top": 51.81,
            "right": 0,
            "bottom": 48,
            "left": 0
          },
          "systemBarsPx": {
            "top": 136,
            "right": 0,
            "bottom": 126,
            "left": 0
          },
          "displayCutout": {
            "top": 51.81,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "displayCutoutPx": {
            "top": 136,
            "right": 0,
            "bottom": 0,
            "left": 0
          },
          "cutoutShape": {
            "xDp": 182.86,
            "yDp": 0,
            "widthDp": 55.24,
            "heightDp": 51.81,
            "rightDp": 173.33,
            "bottomDp": 862.48,
            "xPx": 480,
            "yPx": 0,
            "widthPx": 145,
            "heightPx": 136,
            "rightPx": 455,
            "bottomPx": 2264
          },
          "condition": {
            "android": "17",
            "note": "Android Emulator 37.1.11.0 running the pixel_7 device profile with its AOSP skin, system image CE2A.260420.019 (Android 17, API 37). Portrait rotation 0, default 420 dpi and font scale 1. InsetsProbe 1.5.0 reported a 1080×2400 px window. These are the values the framework reports for the emulator profile, not a Pixel hardware measurement. View rotation does not measure landscape insets.",
            "emulator": {
              "deviceProfile": "pixel_7",
              "skin": "pixel_7",
              "systemImage": "system-images/android-37.0/google_apis_playstore/arm64-v8a",
              "buildFingerprint": "google/sdk_gphone64_arm64/emu64a:17/CE2A.260420.019/15611780:user/release-keys",
              "emulatorVersion": "37.1.11.0",
              "manifestUrl": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-7/emulator-2026-09-27/manifest.json"
            }
          },
          "sources": [
            {
              "kind": "emulator",
              "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_7 profile, 3-button",
              "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-7/emulator-2026-09-27/main-threeButton.json",
              "retrievedAt": "2026-09-27"
            }
          ]
        }
      },
      "sources": [
        {
          "kind": "official",
          "label": "Google Pixel phone hardware tech specs",
          "url": "https://support.google.com/pixelphone/answer/7158570?hl=en",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "official",
          "label": "AOSP Android Emulator skin pixel_7 (Apache 2.0)",
          "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_7",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_7 profile, gestures",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-7/emulator-2026-09-27/main-gesture.json",
          "retrievedAt": "2026-09-27"
        },
        {
          "kind": "emulator",
          "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_7 profile, 3-button",
          "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-7/emulator-2026-09-27/main-threeButton.json",
          "retrievedAt": "2026-09-27"
        }
      ]
    }
  ],
  "sources": [
    {
      "kind": "official",
      "label": "Google Pixel phone hardware tech specs",
      "url": "https://support.google.com/pixelphone/answer/7158570?hl=en",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "official",
      "label": "AOSP Android Emulator skin pixel_7 (Apache 2.0)",
      "url": "https://android.googlesource.com/platform/tools/adt/idea/+/ca26f0383e6cca7c3fe55ccbbe5526ba4e24d198/artwork/resources/device-art-resources/pixel_7",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_7 profile, gestures",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-7/emulator-2026-09-27/main-gesture.json",
      "retrievedAt": "2026-09-27"
    },
    {
      "kind": "emulator",
      "label": "InsetsProbe 1.5.0 on Android Emulator, pixel_7 profile, 3-button",
      "url": "https://github.com/easyhooon/windowinsets.info/blob/main/measurements/pixel-7/emulator-2026-09-27/main-threeButton.json",
      "retrievedAt": "2026-09-27"
    }
  ]
};
